config/routes.rb
Rails.application.routes.draw do

  resources :cars

  resources :manufacturers

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer, presence: true
  validates :color, presence: true
  validates :year, presence: true, inclusion: { in: 1920..Date.today.year }, format: { with: /(19|20)\d{2}/i,
    message: "should be a four-digit year" }
  validates :mileage, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.limit(100)
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car, notice: "Car was successfully created."
    else
      render :new, notice: "Your car could not be saved."
    end
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage)
  end

end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.limit(100)
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      redirect_to @manufacturer, notice: "Manufacturer was successfully created."
    else
      render :new, notice: "Your manufacturer could not be saved."
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h3>All Cars</h3>

<ol>
<% @cars.each do |car| %>
  <li>
    <ul>
      <li><strong>Manufacturer:</strong> <%= car.manufacturer.name %></li>
      <li><strong>Color:</strong> <%= car.color %></li>
      <li><strong>Year:</strong> <%= car.year %></li>
      <li><strong>Mileage:</strong> <%= car.mileage %></li>
      <li><strong><%= link_to "View Car", car_path(car) %></strong></li>
    </ul>
  </li>
  <br>
<% end %>
</ol>

app/views/cars/new.html.erb
<h3>Create Manufacturer</h3>

<%= form_for @car do |f| %>

<% if @car.errors.any? %>

    <p>
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </p>

  <% end %>

  <p>
    <%= f.label :manufacturer %>
    <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name)%>
  </p>

  <p>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </p>

  <p>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.label :mileage %>
    <%= f.text_field :mileage %>
  </p>

  <%= f.submit %>

<% end %>

app/views/cars/show.html.erb
  <h3>Car #<%= @car.id %></h3>

    <ul>
      <li><strong>Manufacturer:</strong> <%= @car.manufacturer.name %></li>
      <li><strong>Color:</strong> <%= @car.color %></li>
      <li><strong>Year:</strong> <%= @car.year %></li>
      <li><strong>Mileage:</strong> <%= @car.mileage %></li>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1> Car Listings </h1>


<h2><%= link_to "All Cars", cars_path %> | <%= link_to "Add Car", new_car_path %> | <%= link_to "All Manufacturers", manufacturers_path %> | <%= link_to "Add Manufacturer", new_manufacturer_path %></h2>

  <p>
    <%= flash[:notice] %>
  </p>
  <p>
    <%= flash[:alert] %>
  </p>

  <%= yield %>
</body>
</html>

app/views/manufacturers/index.html.erb
<h3>All Manufacturers</h3>

<ol>
<% @manufacturers.each do |manufacturer| %>

  <li>
    <strong>Name:</strong> <%= manufacturer.name %>,
    <strong>Country:</strong> <%= manufacturer.country %>
    <strong><%= link_to "(View Manufacturer)", manufacturer_path(manufacturer) %></strong>
  </li>

<% end %>
</ol>

app/views/manufacturers/new.html.erb
<%= form_for @manufacturer do |f| %>

 <% if @manufacturer.errors.any? %>

    <p>
      <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </p>

  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :country %>
    <%= f.text_field :country %>
  </p>

  <%= f.submit %>

<% end %>

app/views/manufacturers/show.html.erb
<h3>Manufacturer #<%= @manufacturer.id %></h3>

  <strong>Name:</strong> <%= @manufacturer.name %>
  <strong>Country:</strong> <%= @manufacturer.country %>